version: "2"

services:
  chrome:
    image: "selenium/standalone-chrome:120.0"
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
  testcontainer:
    build: .
    depends_on:
      - chrome